In [ ]:
# Library used in data analytics
# data structure - n - dimensional array to perform matrix and math operations easily

In [1]:
# reasons why numpy
# pip- package installer for python
# 1. memory usage
import numpy as np
import time
import sys
# creating numpy array
array_numpy = np.arange(100)
print("size of numpy array", array_numpy.size * array_numpy.itemsize)

size of numpy array 400


In [2]:
list_range = range(0, 100)
print("size of list: ", sys.getsizeof(1)*len(list_range))

size of list:  2800


In [4]:
# 2. convenient
#3. faster
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(a1+ a2)

[5 7 9]


In [ ]:
'''
Install
!pip install numpy 
!conda install numpy--y
!pip3 install numpy
'''

In [6]:
import numpy as n
arr = n.array([1,2,3,5])

In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
type(arr[0])

numpy.int32

In [9]:
arr = np.array([1,2,3,4,'Inceptez'])#since it has got string here it l tke evrythng as string since itz homogenous
print(type(arr[0]))

<class 'numpy.str_'>


In [10]:
arr = np.array([1,2,3,4]) #array should be homogenous and it ll take size of largest data
print(type(arr[0]))

<class 'numpy.int32'>


In [11]:
arr_2d = np.array([[1,2,3], [2,3,4]])
arr_2d

array([[1, 2, 3],
       [2, 3, 4]])

In [12]:
arr_2d.shape # shape - no.of rows, no.of columns

(2, 3)

In [15]:
arr_2d = np.array([[1,2,3], [2,3]])
arr_2d #shows warning

<ipython-input-15-ebdde4f32eb4>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr_2d = np.array([[1,2,3], [2,3]])


array([list([1, 2, 3]), list([2, 3])], dtype=object)

In [18]:
arr_2d = np.array([[1,2,3], [2,3,0]])
arr_2d 

array([[1, 2, 3],
       [2, 3, 0]])

In [19]:
#functions involved in creating an array
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
a.reshape((4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
a.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [21]:
a.reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [22]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
a.reshape((4,4))

ValueError: cannot reshape array of size 15 into shape (4,4)

In [23]:
# linspace: This function creates elements which are equally spaced from each other
# (start, stop, count of elements (starting and ending num is incl))
# end number will be excluded or included it is optional
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [28]:
np.linspace(0, 100, 9)

array([  0. ,  12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5, 100. ])

In [25]:
#arange 
#(start, stop, step(end value will be excluded))
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
np.linspace(0, 100, 5, endpoint = False) #end number excluded

array([ 0., 20., 40., 60., 80.])

In [39]:
np.linspace(0, 100, 9)[1:]#removes starting point

array([ 12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5, 100. ])

In [29]:
#square matrix: no.of rows = no.of columns
np.eye(3) #identity matrix: diagonals are 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.linspace(1,1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
np.linspace(1,1,1)

array([1.])

In [35]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [73]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
np.eye(3,4)#creates identity matrix (i.e) 1 in diagonals and zeros elsewhere

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [37]:
np.zeros((3,3))#fills zero in specified shape

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.ones((2,3))#fills 1 in shape specified

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.eye((3))[::-1]#anti identity matrix (anti diagonals are 1)

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [41]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [49]:
np.eye(3, k=-2)#look at the docstring for negative & positive values and syntax

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [43]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [50]:
#operations with numpy array
arr = np.array([20,30,40])
dup = arr.copy()
arr[0] = 60
print(arr)
print(dup)

[60 30 40]
[20 30 40]


In [51]:
#operations with numpy array
arr = np.array([20,30,40])
dup = arr.view()
arr[0] = 60
print(arr)
print(dup)

[60 30 40]
[60 30 40]


In [52]:
#iterations through array
#for loops - n of these arrays
for i in arr:
    print(i)

60
30
40


In [54]:
arr_2d

array([[1, 2, 3],
       [2, 3, 0]])

In [53]:
for i in arr_2d:
    print(i)

[1 2 3]
[2 3 0]


In [55]:
#2d matrix needs 2 loops to fetch each element
#3d matrix needs 3 loops
for i in arr_2d: 
    for x in i:
        print(x)

1
2
3
2
3
0


In [56]:
arr_3d = np.array([[[1,6,8], [6,7,8], [10,21,24]]])
arr_3d

array([[[ 1,  6,  8],
        [ 6,  7,  8],
        [10, 21, 24]]])

In [58]:
# 3d should have 2 sq brackets- 1 for room, the next bracket for 2 dimension, next bracket for elements
arr_3d.shape

(1, 3, 3)

In [65]:
arr_3d = np.array([[[1,6,8], [6,7,8], [10,21,24],[23,25,26]]])
arr_3d

array([[[ 1,  6,  8],
        [ 6,  7,  8],
        [10, 21, 24],
        [23, 25, 26]]])

In [66]:
arr_3d.shape #3d - room, row, column 
#2d - row, column

(1, 4, 3)

In [69]:
for room in arr_3d:
    print(room)
    for each_row in room:
        print("{}.row".format(each_row))
        for data_scientist in each_row:
            print(data_scientist)

[[ 1  6  8]
 [ 6  7  8]
 [10 21 24]
 [23 25 26]]
[1 6 8].row
1
6
8
[6 7 8].row
6
7
8
[10 21 24].row
10
21
24
[23 25 26].row
23
25
26


In [83]:
# addition, subtraction, multiplication
arr2 = np.array(range(10,170,10))
arr2 = arr2.reshape(4,4)

In [84]:
arr2

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [86]:
arr1 = np.array(range(1,17,1))
arr1 = arr1.reshape(4,4)

In [87]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [88]:
arr1 + arr2

array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 110, 121, 132],
       [143, 154, 165, 176]])

In [89]:
arr2 - arr1

array([[  9,  18,  27,  36],
       [ 45,  54,  63,  72],
       [ 81,  90,  99, 108],
       [117, 126, 135, 144]])

In [105]:
np.add(arr1, arr2)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [91]:
np.subtract(arr2, arr1)

array([[  9,  18,  27,  36],
       [ 45,  54,  63,  72],
       [ 81,  90,  99, 108],
       [117, 126, 135, 144]])

In [92]:
np.subtract(arr1, arr2)

array([[  -9,  -18,  -27,  -36],
       [ -45,  -54,  -63,  -72],
       [ -81,  -90,  -99, -108],
       [-117, -126, -135, -144]])

In [93]:
np.multiply(arr1, arr2)

array([[  10,   40,   90,  160],
       [ 250,  360,  490,  640],
       [ 810, 1000, 1210, 1440],
       [1690, 1960, 2250, 2560]])

In [94]:
np.divide(arr1, arr2)

array([[0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1]])

In [95]:
arr1 * arr2

array([[  10,   40,   90,  160],
       [ 250,  360,  490,  640],
       [ 810, 1000, 1210, 1440],
       [1690, 1960, 2250, 2560]])

In [96]:
arr1 / arr2

array([[0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1]])

In [102]:
np.absolute([-1.2, 1.2])

array([1.2, 1.2])

In [107]:
np.where(arr2 > 100)

(array([], dtype=int64), array([], dtype=int64))

In [108]:
np.sum(arr1)

136

In [115]:
arr2 = np.array(range(10,170,10))
arr2 = arr2.reshape(4,4)

In [116]:
np.sum(arr1, arr2)

TypeError: only integer scalar arrays can be converted to a scalar index

In [117]:
np.sum(arr2)

1360

In [111]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [113]:
arr2 = np.array(range(10,170,10))
arr2 = arr2.reshape(4,4)

In [114]:
arr2

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [120]:
#matrix multiplication or dot product
arr1 = np.array([[1,2], [3,5]])
arr2 = np.array([[2,3],[4,5]])

In [121]:
arr1

array([[1, 2],
       [3, 5]])

In [122]:
arr2

array([[2, 3],
       [4, 5]])

In [123]:
np.dot(arr1, arr2)

array([[10, 13],
       [26, 34]])

In [125]:
arr1 ** arr2

array([[   1,    8],
       [  81, 3125]], dtype=int32)

In [126]:
a = np.array([[2,3,6], [4,5,7]])
b = np.array([[2,5,6], [7,8,7], [9,10,8]])

In [127]:
np.dot(a,b) #row no from 1st matrix and column no from 2nd matrix will be the result (i.e) 2* 3  provided the column of 1st matrix and row of 2nd matrix is of same no (i.e) both has got equal no of elements

array([[ 79,  94,  81],
       [106, 130, 115]])

In [133]:
# join numpy arrays
arr1 = np.array([2,3,6])
arr2 = np.array([5,6,7])

In [134]:
np.stack((arr1, arr2), axis = 0)

array([[2, 3, 6],
       [5, 6, 7]])

In [135]:
np.stack((arr1, arr2), axis = 1)

array([[2, 5],
       [3, 6],
       [6, 7]])

In [144]:
arr3 = np.stack((arr1, arr2), axis = 1)
arr3

array([[2, 5],
       [3, 6],
       [6, 7]])

In [146]:
res = []
k =1
for sub in arr3:
    res.append(sub[k])
res

[5, 6, 7]

In [147]:
#transpose
arr3.T

array([[2, 3, 6],
       [5, 6, 7]])

In [148]:
arr1 = np.array([26, 30, 6])
arr2 = np.array([25, 6, 7])
arr3 = np.stack((arr1, arr2), axis = 0)

In [149]:
arr3

array([[26, 30,  6],
       [25,  6,  7]])

In [150]:
np.sort(arr3)#sorts listwise

array([[ 6, 26, 30],
       [ 6,  7, 25]])

In [151]:
arr1 = np.array([26, 30, 6])
arr2 = np.array([25, 6, 7])
arr3 = np.stack((arr1, arr2), axis = 1)

In [152]:
arr3

array([[26, 25],
       [30,  6],
       [ 6,  7]])

In [153]:
np.sort(arr3)

array([[25, 26],
       [ 6, 30],
       [ 6,  7]])