In [172]:
# array with values ranging from 12 to 38
import numpy as np
arr = np.arange(12, 38)
arr

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [25]:
# adding a border around the existing array
a = np.array([[1,1,1], [1,1,1], [1,1,1]])
a = np.pad(a, pad_width = 1)
a

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [24]:
# adding a border around the existing array
a = np.array([[1,1,1], [1,1,1], [1,1,1]])
a = np.pad(a, pad_width = 2)
a

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [6]:
# converting list into array
list_1 = [1,2,3,4,5,6,7, 8]
arr_1 = np.asarray(list_1)
print(arr_1)

[1 2 3 4 5 6 7 8]


In [7]:
# converting a tuple into array
tuple_1 = ([8,4,6], 1,2,3)
arr_2 = np.asarray(tuple_1)
print(arr_2)

[list([8, 4, 6]) 1 2 3]


C:\Users\Balaji\anaconda3\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [8]:
# converting a tuple into array
tup = ("s", 1, "b", 30)
ar = np.asarray(tup)
ar

array(['s', '1', 'b', '30'], dtype='<U2')

In [9]:
# converting Centigrade degrees into Fahrenheit degrees
val_c = [0,12,45.21,34,99.91]
arr_c = np.asarray(val_c)
print("Centigrade degree array: ", arr_c)
arr_f = ((9* arr_c)/5)+ 32
print("Fahrenheit degree array: ", arr_f)

Centigrade degree array:  [ 0.   12.   45.21 34.   99.91]
Fahrenheit degree array:  [ 32.     53.6   113.378  93.2   211.838]


In [18]:
arr_3 = np.array([1,5,30,9,6], dtype = 'f') #conversion to float
print(arr_3)
print(arr_3.dtype) #to print data type
arr_3 = arr_3.astype(int) #conversion to int
print(arr_3)
print(arr_3.dtype)
print("dimension of array: ", arr_3.ndim)# to find the dimension of array
arr_3 = np.array(arr_3, ndmin = 3) #to make into 3D
print(arr_3)
print("dimension of array: ", arr_3.ndim)

[ 1.  5. 30.  9.  6.]
float32
[ 1  5 30  9  6]
int32
dimension of array:  1
[[[ 1  5 30  9  6]]]
dimension of array:  3


In [20]:
#slicing
arr_4 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr_4[1, 1:4])

[7 8 9]


In [19]:
arr_5 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr_5[0:2, 1:4])#Slices elements in index 1, 2, 3 in both the arrays since criteria is mentioned 0:2

[[2 3 4]
 [7 8 9]]


In [21]:
arr6 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr6.reshape(2, 3, 2) #reshapes into 3D where it should have 2 arrays with 3 rows and 2 columns each
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [22]:
arr7 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr7): #to access individual values
  print(x)

1
2
3
4
5
6
7
8


In [23]:
arr8 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr8): #to access index of individual elements along with its values
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [39]:
# no.of elements of array, length of array element in bytes & total bytes consumed by the elements
b = np.linspace(0,9,5)
print(b)
print("length of array: ", len(b))
print("size of array: ", b.size)
print("length of one array element in bytes: ", b.itemsize)
print("total bytes consumed by the elements of array: ", b.nbytes)

[0.   2.25 4.5  6.75 9.  ]
length of array:  5
size of array:  5
length of one array element in bytes:  8
total bytes consumed by the elements of array:  40


In [42]:
# Get the unique elements of an array
c = np.array([1,2,2,3,3,5,30,9,6])
print("original array: ", c)
new_c = np.unique(c)
print("unique array: ", new_c)

original array:  [ 1  2  2  3  3  5 30  9  6]
unique array:  [ 1  2  3  5  6  9 30]


In [51]:
# dimension change of array
original_arr = np.array([1,2,3,4,5,6,7,8,9])
print("Original array: ", original_arr)
print(original_arr.ndim)
print(np.shape(original_arr))
changed_arr = original_arr.reshape(3,3)
print("changed array: ", changed_arr)
print(changed_arr.ndim)
print(np.shape(changed_arr))

Original array:  [1 2 3 4 5 6 7 8 9]
1
(9,)
changed array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [54]:
# dimension change of array
original_arr = np.array([1,2,3,4,5,6,7,8,9])
print("Original array: ", original_arr)
changed_arr = np.array(original_arr, ndmin = 3)
print("Dimension changed array: ", changed_arr)
print(changed_arr.ndim)

Original array:  [1 2 3 4 5 6 7 8 9]
Dimension changed array:  [[[1 2 3 4 5 6 7 8 9]]]
3


In [55]:
# Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive
d = np.linspace(2.5, 6.5, 30)
print(d)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


In [58]:
# Convert 1-D arrays as columns into a 2-D array
array1 = np.array([10,20,30])
array2 = np.array([40,50,60])
array3 = np.stack((array1,array2),axis=1)
print(array3)


[[10 40]
 [20 50]
 [30 60]]


In [73]:
# joining
array1 = np.array([10,20,30])
array2 = np.array([40,50,60])
array3 = np.concatenate((array1,array2))
print(array3)

[10 20 30 40 50 60]


In [74]:
# joining
array1 = np.array([10,20,30])
array2 = np.array([40,50,60])
array3 = np.hstack((array1,array2))
print(array3)

[10 20 30 40 50 60]


In [75]:
# joining
array1 = np.array([10,20,30])
array2 = np.array([40,50,60])
array3 = np.vstack((array1,array2))
print(array3)

[[10 20 30]
 [40 50 60]]


In [76]:
# joining
array1 = np.array([10,20,30])
array2 = np.array([40,50,60])
array3 = np.dstack((array1,array2))
print(array3)

[[[10 40]
  [20 50]
  [30 60]]]


In [100]:
# Create a 5x5 matrix with row values ranging from 0 to 4
e = np.zeros((5,5))
print("original: ", e)
f = e + np.arange(5)
print("reconstructed: ", f)

original:  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
reconstructed:  [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [110]:
# Sum of all the multiples of 3 or 5 below 100
g = np.arange(1, 100)
h= g[(g % 3 == 0) | (g % 5 == 0)]
print(h)
print(h.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [124]:
# Combine a one and a two dimensional array together and display their elements
i = np.arange(4)
print("1D array: ", i)
j = np.arange(8)
k = j.reshape(2,4)
print("2D array: ", k)
for l,m in np.nditer([i,k]):
    print(l, ':', m)

1D array:  [0 1 2 3]
2D array:  [[0 1 2 3]
 [4 5 6 7]]
0 : 0
1 : 1
2 : 2
3 : 3
0 : 4
1 : 5
2 : 6
3 : 7


In [126]:
# replace all elements of NumPy array that are greater than specified array
n = np.array([[ 0.42436315, 0.48558583, 0.32924763], [ 0.7439979,0.58220701,0.38213418], [ 0.5097581,0.34528799,0.1563123 ]])
print("Original array:" , n)
n[n>0.5] = 0.5
print("reconstructed array:", n)

Original array: [[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
reconstructed array: [[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


In [153]:
# Add a new row to an empty numpy array
o = np.empty((0,3), int)
print("empty array: ", o)
o = np.append(o, np.array([[10,20,30]]), axis = 0)
print(o)
o = np.append(o, np.array([[40,50,60]]), axis = 0)
print(o)

empty array:  []
[[10 20 30]]
[[10 20 30]
 [40 50 60]]


In [162]:
# join a sequence of arrays along a new axis
p = np.array([1,2,3])
q = np.array([4,5,6])
r = np.vstack((p,q))
print(r)

[[1 2 3]
 [4 5 6]]


In [166]:
# join a sequence of arrays along a new axis
s = np.array([[1],[2],[3]])
t = np.array([[5],[6],[7]])
u = np.vstack((s,t))
print(u)

[[1]
 [2]
 [3]
 [5]
 [6]
 [7]]


In [174]:
# search
ar1 = np.arange(9)
print(ar1)
sar1 = np.where((ar1 == 4))
print(sar1)

[0 1 2 3 4 5 6 7 8]
(array([4], dtype=int64),)


In [178]:
# search 
ar1 = np.arange(9)
print(ar1)
sar1 = np.searchsorted(ar1, 9)
print(sar1)

[0 1 2 3 4 5 6 7 8]
9


In [180]:
# search 
ar1 = np.arange(9)
print(ar1)
sar1 = np.searchsorted(ar1, 5)
print(sar1)

[0 1 2 3 4 5 6 7 8]
5


In [183]:
# search 
ar1 = np.array([9,10,11,12,13,14])
print(ar1)
sar1 = np.searchsorted(ar1, 10)
print(sar1)

[ 9 10 11 12 13 14]
1


In [184]:
# split 
ar1 = np.array([9,10,11,12,13,14])
print(ar1)
sar1 = np.array_split(ar1, 2) #splits array into 2 since we gave 2
print(sar1)

[ 9 10 11 12 13 14]
[array([ 9, 10, 11]), array([12, 13, 14])]


In [186]:
# split 
ar1 = np.array([9,10,11,12,13])
print(ar1)
sar1 = np.array_split(ar1, 2) #splits array into 2 since we gave 2
print(sar1)

[ 9 10 11 12 13]
[array([ 9, 10, 11]), array([12, 13])]


In [185]:
# sort 
ar1 = np.array([9,0,1,12,5,14])
print(ar1)
sar1 = np.sort(ar1)
print(sar1)

[ 9  0  1 12  5 14]
[ 0  1  5  9 12 14]


In [192]:
ar1 = np.array([9,0,1,12,5,14])
print(ar1)
sar1 = [True, False, False, True, True, False]
ar2 = ar1[sar1]
print(ar2)

[ 9  0  1 12  5 14]
[ 9 12  5]
